# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4c558c8071321de6f0024727ffd885b5ca895b99d26e597dd9d53295f574137acc0d0a079fbb8e3e171b2111ffd81a7a7b17a11833a63a7059324ba4130579d

test:
  secret_key_base: bfc51b469b4a4c35f0286f1572a930a9977061271c61fed63722ffab752cee62468e00682d196d7b0920cbacc57cca59c038fa9108ce9ab93ca46f10db0298af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
